subject_id_col: patient_id

code_status:
  status:
    code:
      - CODE_STATUS
      - col(code_status_category)
    time: col(start_dttm)
    time_format: "%Y-%m-%d %H:%M:%S"
    patient_id: patient_id
