subject_id_col: patient_id

patient:
  sex:
    code:
      - DEMO
      - sex
      - col(sex_category)
    time: null

  race:
    code:
      - DEMO
      - race
      - col(race_category)
    time: null

  ethnicity:
    code:
      - DEMO
      - ethnicity
      - col(ethnicity_category)
    time: null

  birth:
    code: MEDS_BIRTH
    time: col(birth_date)
    time_format:
      - "%Y-%m-%d %H:%M:%S"
      - "%Y-%m-%d"

  death:
    code: MEDS_DEATH
    time: col(death_dttm)
    time_format:
      - "%Y-%m-%d %H:%M:%S"
      - "%Y-%m-%d"
